# Generated by Django 3.2.4 on 2021-07-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customer_data_de_nascimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descrition',
            new_name='detalhes',
        ),
        migrations.AddField(
            model_name='product',
            name='margem',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='preco_de_compra',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantidade_em_estoque',
            field=models.FloatField(null=True),
        ),
    ]
