# Generated by Django 3.2.4 on 2021-07-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210720_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preco_do_produto',
            field=models.FloatField(null=True),
        ),
    ]
